# terminal (ghostty-toggle)
<Control><Alt>t,ghostty,com.fiedor.Ghostty,

# VsCode
<Control><Alt>v,code,code
# Zed
<Control><Alt>z,zed,zed

# projects / home / screenshots / screencasts / downloads (Files/Nautilus)
# NOTE: Update paths below to match your username
<Control><Alt>p,nautilus /home/fiedor/Projects,org.gnome.Nautilus,/Projects/
<Control><Alt>h,nautilus /home/fiedor/,org.gnome.Nautilus,/Home|fiedor/
<Control><Alt>a,nautilus /home/fiedor/Pictures/Screenshots,org.gnome.Nautilus,/Screenshots/
<Control><Alt>x,nautilus /home/fiedor/Videos/Screencasts,org.gnome.Nautilus,/Screencasts/
<Control><Alt>f,nautilus /home/fiedor/Downloads,org.gnome.Nautilus,/Downloads/
