#!/usr/bin/expect -f

# Define variables
set user "ai"         ;# Replace with your Raspberry Pi username
set host "192.168.5.240"       ;# Replace with your Raspberry Pi IP address or hostname
set password "transformerą"     ;# Replace with your password

# Start SSH session with X11 forwarding
spawn ssh $user@$host
expect "password:"
send "$password\r"

# Wait for the shell prompt
# expect "$ "
sleep 0.2
# Change directory
# send "cd /home/KNR/KNR-dron/\r"

# Keep the session open
# send "/bin/zsh\r"

# Interact with the session to prevent it from closing
interact

